use crate::ReviewCapture::*;
use crate::ReviewEffort::*;
use crate::ReviewSelection::*;
use crate::ReviewSurface::*;
use crate::{ReviewKeystrokes, ReviewRequirements, ReviewSolutionProperties};
use clap::ValueEnum;
use serde::{Deserialize, Serialize};
use strum::EnumIter;

macro_rules! review_solutions {
    ($($variant:ident { $($field:ident: $value:expr),+ $(,)? }),+ $(,)?) => {
        #[derive(ValueEnum, EnumIter, Serialize, Deserialize, Eq, PartialEq, Hash, Clone, Copy, Debug)]
        #[value(rename_all = "kebab-case")]
        pub enum ReviewSolution {
            $($variant),+
        }

        impl ReviewSolution {
            pub fn properties(self) -> ReviewSolutionProperties {
                use ReviewSolution::*;
                match self {
                    $($variant => ReviewSolutionProperties { $($field: $value),+ }),+
                }
            }
        }
    };
}

review_solutions! {
    ClipboardAndReviewEditor {
        surface: Terminal,
        effort: Configuration,
        capture: RenderedText,
        selection: Characters,
        keyboard_selection: false,
        requires_hosted_review: false,
        workflow: "Copy the selected diff into a persistent Markdown review, type the comment below it, and repeat; copy or attach the complete review to the originating thread.",
        tradeoff: "Minimal setup, but repeated copying, focus changes, formatting, and returning to the diff cost keys; terminal text can lose layout and location information.",
    },
    DesktopClipboardHotkey {
        surface: Desktop,
        effort: Adapter,
        capture: RenderedText,
        selection: Characters,
        keyboard_selection: false,
        requires_hosted_review: false,
        workflow: "After copying a selection, invoke a global shortcut that opens a comment form; save appends quote and comment and restores focus; Finish delivers the draft.",
        tradeoff: "Works across applications, but copying remains a separate action and the clipboard does not identify the producing repository or thread.",
    },
    Iterm2SelectionScript {
        surface: Iterm2,
        effort: Adapter,
        capture: RenderedText,
        selection: Characters,
        keyboard_selection: true,
        requires_hosted_review: false,
        workflow: "Use iTerm2 selection or Copy Mode, invoke a bound Python API function to read the selection and open a comment form, then save and return automatically; Finish sends the draft.",
        tradeoff: "Keeps the current terminal and removes explicit copy/paste; the adapter must associate the pane with a review, and rendered selections can contain gutters or wrapped lines.",
    },
    Iterm2ScrollbackEditor {
        surface: Iterm2,
        effort: Adapter,
        capture: RenderedText,
        selection: Characters,
        keyboard_selection: true,
        requires_hosted_review: false,
        workflow: "Export pane text through the terminal API into a read-only editor buffer; use visual selection plus a comment mapping to append to the review; Finish sends it.",
        tradeoff: "Editor motions improve selection, but exporting and entering the editor adds a transition and cannot restore metadata already lost in terminal rendering.",
    },
    Iterm2HunkActions {
        surface: Iterm2,
        effort: Extension,
        capture: PatchSnapshotWithCoordinates,
        selection: WholeHunks,
        keyboard_selection: true,
        requires_hosted_review: false,
        workflow: "Render frozen hunks with stable identifiers and add a keyboard action to choose an identifier, open its comment form, and append the original hunk; Finish sends the review.",
        tradeoff: "Avoids dragging or marking a whole hunk; requires a custom renderer and picker, and hunk selection cannot express a smaller range.",
    },
    KittySelectionOverlay {
        surface: Kitty,
        effort: Adapter,
        capture: RenderedText,
        selection: Characters,
        keyboard_selection: false,
        requires_hosted_review: false,
        workflow: "Select terminal text and bind launch with the selection as stdin to a comment overlay; saving appends the quote and closes the overlay; Finish delivers the draft.",
        tradeoff: "A compact capture-and-comment action, but requires changing terminals; keyboard selection needs an additional mechanism and screen text has no reliable patch coordinates.",
    },
    KittyScrollbackNeovim {
        surface: Kitty,
        effort: Adapter,
        capture: RenderedText,
        selection: Characters,
        keyboard_selection: true,
        requires_hosted_review: false,
        workflow: "Open scrollback in Neovim using a kitten integration; select with editor motions and invoke a quote/comment mapping; save restores the review cursor and Finish sends the draft.",
        tradeoff: "Powerful keyboard selection across scrollback, with terminal and editor integration to maintain; captured text remains a rendered transcript.",
    },
    KittyHunkHints {
        surface: Kitty,
        effort: Extension,
        capture: PatchSnapshotWithCoordinates,
        selection: WholeHunks,
        keyboard_selection: true,
        requires_hosted_review: false,
        workflow: "Give frozen diff hunks stable hint targets; a custom hints handler resolves the chosen hunk and opens the comment overlay; save appends it and Finish sends the review.",
        tradeoff: "Short labels can replace repeated navigation, but require custom target recognition and resolve entire hunks rather than arbitrary selections.",
    },
    WeztermCopyModeLua {
        surface: Wezterm,
        effort: Adapter,
        capture: RenderedText,
        selection: Characters,
        keyboard_selection: true,
        requires_hosted_review: false,
        workflow: "Select in Copy Mode and invoke a Lua binding that obtains pane selection text and launches the comment form; save appends and restores focus; Finish sends the draft.",
        tradeoff: "Supports keyboard capture without the clipboard; requires changing terminals and preserving the original pane's review identity across callbacks.",
    },
    WeztermQuickSelectHunks {
        surface: Wezterm,
        effort: Extension,
        capture: PatchSnapshotWithCoordinates,
        selection: WholeHunks,
        keyboard_selection: true,
        requires_hosted_review: false,
        workflow: "Render stable hunk labels and match them with Quick Select; its action resolves the frozen hunk and opens a comment form; save appends and Finish sends.",
        tradeoff: "Keyboard labels can reduce navigation; Quick Select matches patterns, so the adapter must supply hunk identifiers and cannot treat it as arbitrary range selection.",
    },
    TmuxCopyPipePopup {
        surface: Tmux,
        effort: Adapter,
        capture: RenderedText,
        selection: Characters,
        keyboard_selection: true,
        requires_hosted_review: false,
        workflow: "Select in copy-mode and bind copy-pipe to retain the selection and open a comment popup; save appends quote and comment and closes the popup; Finish sends the draft.",
        tradeoff: "Keeps iTerm2 and can run beside a remote agent; copy-mode entry and prefix keys cost actions unless remapped, and pane text may already be lossy.",
    },
    TmuxPersistentReviewPane {
        surface: Tmux,
        effort: Adapter,
        capture: PatchSnapshot,
        selection: Characters,
        keyboard_selection: true,
        requires_hosted_review: false,
        workflow: "Keep a frozen patch in an editor in a persistent review pane; select and comment through a mapping, accumulating the draft there; one Finish binding delivers it.",
        tradeoff: "Amortizes opening the editor and retains a review across terminal reattachment; costs screen space and needs explicit pane-to-thread routing.",
    },
    TmuxHunkPickerPopup {
        surface: Tmux,
        effort: Adapter,
        capture: PatchSnapshotWithCoordinates,
        selection: WholeHunks,
        keyboard_selection: true,
        requires_hosted_review: false,
        workflow: "Open a persistent hunk picker in a popup, choose a frozen hunk, type a comment, and return to the picker after save; Finish sends all comments with their hunks.",
        tradeoff: "Short hunk navigation in any terminal, but a full hunk can overquote the intended selection and popup lifetime must not be the only draft storage.",
    },
    ZellijCopyCommand {
        surface: Zellij,
        effort: Adapter,
        capture: RenderedText,
        selection: Characters,
        keyboard_selection: false,
        requires_hosted_review: false,
        workflow: "Route copied text to an armed review capture helper through copy_command; open a floating comment pane, append on save, and deliver the accumulated draft on Finish.",
        tradeoff: "Selection can launch composition immediately, but copy_command affects ordinary copying too; an explicit review mode prevents unintended captures, and mouse selection is the baseline.",
    },
    ZellijScrollbackEditor {
        surface: Zellij,
        effort: Adapter,
        capture: RenderedText,
        selection: Characters,
        keyboard_selection: true,
        requires_hosted_review: false,
        workflow: "Open scrollback in the configured editor and use a selection-to-comment mapping; save appends to the review and restores selection position; Finish sends it.",
        tradeoff: "Adds keyboard selection using an existing editor, but introduces an editor transition and retains the limitations of captured terminal output.",
    },
    ZellijReviewPlugin {
        surface: Zellij,
        effort: Extension,
        capture: PatchSnapshotWithCoordinates,
        selection: Characters,
        keyboard_selection: true,
        requires_hosted_review: false,
        workflow: "Build a plugin that owns the frozen diff, keyboard range selection, and comment form; save appends and returns to the diff; Finish submits the review to its bound thread.",
        tradeoff: "Can provide direct bindings without copy-mode, but must implement diff rendering, selection, persistence, and host communication within the plugin model.",
    },
    ZleClipboardWidget {
        surface: Zsh,
        effort: Adapter,
        capture: RenderedText,
        selection: Characters,
        keyboard_selection: false,
        requires_hosted_review: false,
        workflow: "Copy a diff selection, return to the shell prompt, and invoke a widget that captures the clipboard and edits a comment while preserving the command buffer; save appends and Finish sends.",
        tradeoff: "Small shell integration, but ZLE edits the command line, not terminal scrollback; it needs a selection source and does not run while a foreground pager owns the terminal.",
    },
    ZleFzfHunkWidget {
        surface: Zsh,
        effort: Adapter,
        capture: PatchSnapshotWithCoordinates,
        selection: WholeHunks,
        keyboard_selection: true,
        requires_hosted_review: false,
        workflow: "Bind a widget to open a picker over frozen hunks, then collect a comment and append it; keep the picker alive for further comments and use Finish to send the review.",
        tradeoff: "Avoids terminal selection entirely, but requires a hunk parser and cannot quote a smaller region without adding a second selection stage.",
    },
    ZleDiffBufferWidget {
        surface: Zsh,
        effort: Extension,
        capture: PatchSnapshot,
        selection: Characters,
        keyboard_selection: true,
        requires_hosted_review: false,
        workflow: "Temporarily load a frozen patch into a dedicated ZLE editing context, use region selection and a comment widget, append on save, then Finish and restore the original command buffer.",
        tradeoff: "Reuses learned shell editing motions, but large multiline patches are awkward; the review context must never execute the patch as a shell command.",
    },
    LessMarkedRangePipe {
        surface: Terminal,
        effort: Adapter,
        capture: PatchSnapshot,
        selection: Lines,
        keyboard_selection: true,
        requires_hosted_review: false,
        workflow: "Page an immutable plain unified diff, mark a range, and pipe the range to a comment helper using a configured less binding; save appends and returns to the pager; Finish sends.",
        tradeoff: "Keeps a familiar pager and original patch bytes; mark-to-screen range semantics take practice, and file or hunk headers can lie outside the selected range.",
    },
    FzfHunkPicker {
        surface: Terminal,
        effort: Adapter,
        capture: PatchSnapshotWithCoordinates,
        selection: WholeHunks,
        keyboard_selection: true,
        requires_hosted_review: false,
        workflow: "Index frozen hunks as picker entries with previews; a binding opens a comment form and returns after append; Finish sends the accumulated review.",
        tradeoff: "Fuzzy search can reach a hunk with few keys; the preview is not a text selector, so selection remains hunk-sized.",
    },
    FzfDiffLinePicker {
        surface: Terminal,
        effort: Extension,
        capture: PatchSnapshotWithCoordinates,
        selection: Lines,
        keyboard_selection: true,
        requires_hosted_review: false,
        workflow: "Index patch lines with stable identities, multi-select entries, reconstruct original ordered ranges, and open one comment form; append on save and Finish sends the review.",
        tradeoff: "Can select disjoint lines, but repeated toggles cost keys; sorting and filtering must not reorder or merge unrelated selected ranges.",
    },
    VimPatchBuffer {
        surface: Vim,
        effort: Adapter,
        capture: PatchSnapshot,
        selection: Characters,
        keyboard_selection: true,
        requires_hosted_review: false,
        workflow: "Open an immutable patch buffer; a visual-mode mapping opens a comment buffer containing the captured selection; one save mapping appends and returns, and Finish sends the review.",
        tradeoff: "Strong range motions with little integration code; raw patch selections need surrounding headers or an additional parser for precise file and side anchors.",
    },
    NeovimVisualComment {
        surface: Neovim,
        effort: Extension,
        capture: PatchSnapshotWithCoordinates,
        selection: Characters,
        keyboard_selection: true,
        requires_hosted_review: false,
        workflow: "Select within a frozen diff buffer, press a single mapped comment key, type into a floating editor, then save-and-return; Finish sends all captured ranges to the originating thread.",
        tradeoff: "A two-action comment loop after selection with no manual focus switch; requires a buffer-to-patch mapping and custom review persistence.",
    },
    NeovimCommentOperator {
        surface: Neovim,
        effort: Extension,
        capture: PatchSnapshotWithCoordinates,
        selection: Characters,
        keyboard_selection: true,
        requires_hosted_review: false,
        workflow: "Define a comment operator that accepts a motion or diff text object, captures that frozen range, and opens composition immediately; save-and-return appends, and Finish sends the review.",
        tradeoff: "Can avoid entering and leaving visual mode; the plugin must implement operator-pending selection and distinguish patch hunk objects from source-language objects.",
    },
    NeovimDiffviewComment {
        surface: Neovim,
        effort: Extension,
        capture: PatchSnapshotWithCoordinates,
        selection: Characters,
        keyboard_selection: true,
        requires_hosted_review: false,
        workflow: "Add visual comment mappings to Diffview buffers; map the chosen old or new side back to the frozen patch, collect the comment, append on save, and send on Finish.",
        tradeoff: "Reuses an established diff navigator; comments and delivery are custom additions, and source selections need reconstruction to preserve diff markers and removed lines.",
    },
    EmacsDiffModeComment {
        surface: Emacs,
        effort: Adapter,
        capture: PatchSnapshot,
        selection: Characters,
        keyboard_selection: true,
        requires_hosted_review: false,
        workflow: "Use diff-mode over a frozen patch and bind a region command to compose a review entry; a save-and-return command appends the entry, and Finish sends the draft.",
        tradeoff: "Reuses region selection and editor composition; a plain region may omit the headers needed to infer file, side, and line coordinates.",
    },
    MagitRegionComment {
        surface: Emacs,
        effort: Extension,
        capture: PatchSnapshotWithCoordinates,
        selection: Lines,
        keyboard_selection: true,
        requires_hosted_review: false,
        workflow: "Bind a Magit command for the active hunk-internal region or section; resolve it against the frozen patch, compose and append a comment, and send the draft on Finish.",
        tradeoff: "Hunk and section navigation reduce selection effort; the integration must respect Magit's distinct region semantics and never use staging as review storage.",
    },
    EmacsEdiffComment {
        surface: Emacs,
        effort: Extension,
        capture: PatchSnapshotWithCoordinates,
        selection: Characters,
        keyboard_selection: true,
        requires_hosted_review: false,
        workflow: "Review frozen versions in Ediff, select a region or current difference, and bind capture plus composition; save restores the comparison and Finish sends all entries.",
        tradeoff: "Good for users fluent in Ediff navigation; the adapter must map comparison buffers and difference regions back to the same patch snapshot.",
    },
    VsCodeSelectionCommand {
        surface: VsCode,
        effort: Extension,
        capture: PatchSnapshotWithCoordinates,
        selection: Characters,
        keyboard_selection: true,
        requires_hosted_review: false,
        workflow: "Bind an extension command to capture the selected diff side and range and open a comment editor; save appends and restores focus, and Finish sends the assembled draft.",
        tradeoff: "Reuses editor selection and configurable shortcuts; the extension must preserve old-side selections and handle buffer edits since the diff was opened.",
    },
    VsCodeCommentController {
        surface: VsCode,
        effort: Extension,
        capture: PatchSnapshotWithCoordinates,
        selection: Lines,
        keyboard_selection: true,
        requires_hosted_review: false,
        workflow: "Implement a CommentController for snapshot documents and bind range comment creation and save; accumulate inline threads locally, then render their original diff excerpts and send on Finish.",
        tradeoff: "Comments remain visible beside code; a local review extension must supply range providers, persistence, efficient focus bindings, and agent delivery.",
    },
    TuicrAdapter {
        surface: Terminal,
        effort: Adapter,
        capture: PatchSnapshotWithCoordinates,
        selection: Lines,
        keyboard_selection: true,
        requires_hosted_review: false,
        workflow: "Use tuicr visual range selection, c to comment, and Enter to save; an adapter joins stored anchors to the retained diff snapshot and sends excerpt-plus-comment entries when review finishes.",
        tradeoff: "Existing keyboard review UI; the documented Markdown export contains anchors and comments, so literal diff excerpts and explicit originating-thread delivery need an adapter.",
    },
    RevdiffAdapter {
        surface: Terminal,
        effort: Adapter,
        capture: PatchSnapshotWithCoordinates,
        selection: SingleLine,
        keyboard_selection: true,
        requires_hosted_review: false,
        workflow: "Review a frozen patch in revdiff, annotate the focused line, then let a wrapper persist its structured output and assemble matching patch excerpts before delivery to the originating thread.",
        tradeoff: "Existing annotation UI and configurable bindings; documented selection is a line, with hunk expansion triggered by comment text, rather than arbitrary ranges. The wrapper must handle its annotated-success exit status.",
    },
    RevdiffRangeExtension {
        surface: Terminal,
        effort: Extension,
        capture: PatchSnapshotWithCoordinates,
        selection: Lines,
        keyboard_selection: true,
        requires_hosted_review: false,
        workflow: "Extend revdiff with keyboard range selection and explicit range export, retain the frozen patch, and bind comment-save-return plus Finish to assemble and deliver the review.",
        tradeoff: "Reuses an existing diff renderer but requires a new range model and integration; arbitrary range selection is a proposed extension, not a documented existing feature.",
    },
    CritBrowserAdapter {
        surface: Browser,
        effort: Adapter,
        capture: PatchSnapshotWithCoordinates,
        selection: Lines,
        keyboard_selection: false,
        requires_hosted_review: false,
        workflow: "Open local changes in Crit, select a line range and write inline comments; an adapter retains the reviewed patch and turns the saved review into excerpt-plus-comment entries for the originating agent.",
        tradeoff: "Existing browser review forms; documented range selection uses clicking and dragging, so a low-keystroke keyboard-only path needs additional verification or customization.",
    },
    GithubPullRequestReview {
        surface: Browser,
        effort: Adapter,
        capture: PatchSnapshotWithCoordinates,
        selection: Lines,
        keyboard_selection: false,
        requires_hosted_review: true,
        workflow: "Collect range comments in a pending GitHub PR review; on Finish, an adapter reads the review and its pinned diff, assembles excerpts, and sends the result to the originating agent thread.",
        tradeoff: "Mature review accumulation, but requires changes available in a PR and API access; submitting a PR review alone does not deliver a prompt to its coding agent.",
    },
    GitlabMergeRequestReview {
        surface: Browser,
        effort: Adapter,
        capture: PatchSnapshotWithCoordinates,
        selection: Lines,
        keyboard_selection: false,
        requires_hosted_review: true,
        workflow: "Collect draft range comments on a GitLab MR; on Finish, resolve them against the reviewed diff version and send the assembled excerpts and comments to the originating agent thread.",
        tradeoff: "Existing draft review support, but requires a hosted MR and a separate agent bridge; browser range selection and focus navigation may cost more actions.",
    },
    BrowserReviewExtension {
        surface: Browser,
        effort: Extension,
        capture: PatchSnapshotWithCoordinates,
        selection: Characters,
        keyboard_selection: true,
        requires_hosted_review: true,
        workflow: "Add keyboard range selection and a single comment shortcut to a hosted diff page; resolve DOM selections to the pinned raw patch, append locally, and deliver through a Finish binding.",
        tradeoff: "Can improve an existing review website's hot path; requires host-specific DOM mapping, especially for virtualized, hidden, or side-by-side lines.",
    },
    LocalBrowserReviewApp {
        surface: Browser,
        effort: Application,
        capture: PatchSnapshotWithCoordinates,
        selection: Characters,
        keyboard_selection: true,
        requires_hosted_review: false,
        workflow: "Serve a frozen patch locally with modal keyboard selection and inline composition; save appends and returns to the range, and a Finish key sends the draft to its recorded agent thread.",
        tradeoff: "Full control over keybindings and visible comments, with browser rendering libraries available; requires a local service, persistence, and editor-quality keyboard behavior.",
    },
    StandaloneReviewTui {
        surface: Terminal,
        effort: Application,
        capture: PatchSnapshotWithCoordinates,
        selection: Characters,
        keyboard_selection: true,
        requires_hosted_review: false,
        workflow: "Build a diff TUI with a comment operator, range and hunk text objects, an inline composer, save-and-return, and a single Finish-and-send binding targeting the recorded originating thread.",
        tradeoff: "Can minimize the entire keyboard path while retaining iTerm2; requires implementing selection, Unicode display mapping, patch parsing, draft recovery, and agent integration.",
    },
    StandaloneDesktopReviewApp {
        surface: Desktop,
        effort: Application,
        capture: PatchSnapshotWithCoordinates,
        selection: Characters,
        keyboard_selection: true,
        requires_hosted_review: false,
        workflow: "Build a desktop diff reviewer with modal keyboard selection, inline comments, persistent review drafts, and a Finish command that sends the complete review to its recorded agent thread.",
        tradeoff: "Can offer rich layout and accessibility with direct shortcuts; window management and packaging add work without inherently reducing key count below an editor or TUI.",
    },
    AgentEmbeddedReviewPane {
        surface: Terminal,
        effort: Application,
        capture: PatchSnapshotWithCoordinates,
        selection: Characters,
        keyboard_selection: true,
        requires_hosted_review: false,
        workflow: "Integrate a frozen diff review pane into the coding agent interface; select and compose inline, save entries locally, and Finish submits them directly to the thread that produced the snapshot.",
        tradeoff: "Avoids external thread selection and handoff focus changes; requires an extensible agent UI or an upstream contribution and explicit behavior for active agent turns.",
    },
    AnnotatedPatchDocument {
        surface: Vim,
        effort: Adapter,
        capture: PatchSnapshot,
        selection: Characters,
        keyboard_selection: true,
        requires_hosted_review: false,
        workflow: "Use an editor mapping to insert review blocks associated with selections in a review copy of a frozen patch; keep the original snapshot separate and send the extracted review on Finish.",
        tradeoff: "All selections and prose can stay in one document; review block delimiters need unambiguous encoding so comments cannot be mistaken for patch content.",
    },
}

impl ReviewSolution {
    pub fn meets(self, requirements: &ReviewRequirements) -> bool {
        let properties = self.properties();
        properties.effort <= requirements.maximum_effort && (!requirements.keyboard_only || properties.keyboard_selection) && (!requirements.local_only || !properties.requires_hosted_review) && (!requirements.require_exact_patch || properties.capture.preserves_exact_patch()) && (!requirements.require_file_and_side || properties.capture.preserves_file_and_side()) && (!requirements.require_partial_hunks || properties.selection.supports_partial_hunks()) && (!requirements.require_multiline_ranges || properties.selection.supports_multiline_ranges()) && (!requirements.require_character_selection || properties.selection == Characters)
    }

    pub fn decide(candidates: impl IntoIterator<Item = Self>, requirements: &ReviewRequirements, mut keystrokes_for_review: impl FnMut(Self) -> ReviewKeystrokes) -> Option<Self> {
        candidates
            .into_iter()
            .filter(|solution| solution.meets(requirements))
            .map(|solution| (keystrokes_for_review(solution), solution.properties().effort, solution))
            .min_by_key(|(keystrokes, effort, _)| (*keystrokes, *effort))
            .map(|(_, _, solution)| solution)
    }
}
